version: '3.8'

services:
  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./src/laravel/public:/var/www/public
      - ./src/laravel/storage/app/public:/var/www/storage/app/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_docker_template

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - ./src/laravel:/var/www
    depends_on:
      - nginx
      - postgresql
      - redis
    networks:
      - laravel_docker_template

  postgresql:
    image: postgres:16.1-alpine
    container_name: postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: laravel_docker_template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - laravel_docker_template

  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 12345
    volumes:
      - redis_data:/data
    networks:
      - laravel_docker_template

networks:
  laravel_docker_template:
    name: laravel_docker_template

volumes:
  postgresql_data:
    name: laravel_docker_template_postgresql_data
  redis_data:
    name: laravel_docker_template_redis_data